In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [2]:
data = pd.ExcelFile("oasdi_zip16.xlsx")

In [3]:
len(data.sheet_names)

56

In [4]:
help(data.parse)

Help on method parse in module pandas.io.excel:

parse(sheet_name=0, header=0, names=None, index_col=None, usecols=None, squeeze=False, converters=None, true_values=None, false_values=None, skiprows=None, nrows=None, na_values=None, parse_dates=False, date_parser=None, thousands=None, comment=None, skipfooter=0, convert_float=True, **kwds) method of pandas.io.excel.ExcelFile instance
    Parse specified sheet(s) into a DataFrame

    Equivalent to read_excel(ExcelFile, ...)  See the read_excel
    docstring for more info on accepted parameters

In [5]:
headers = ['contact_info', 'zip_code', 'nan', 'total', 'retired', 'disabled',
          'widowers_parents', 'spouses', 'children', 'amount_all_beneficiaries', 'amount_retired',
          'amount_widowers', 'old_beneficiaries']

In [6]:
def state_df_parse(input_df):
    """
    """
    all_df = pd.DataFrame()
    
    for state in input_df.sheet_names:
        state_df = input_df.parse(state, names = headers)
        state_df.drop(['contact_info', 'nan'], inplace=True, axis=1)
        state_df.dropna(subset=['zip_code'], inplace=True)
        state_df['state'] = state
        all_df = pd.concat([all_df, state_df], axis=0)
        
    return all_df

In [7]:
all_states = state_df_parse(data)

In [8]:
all_states.head()

,zip_code,total,retired,disabled,widowers_parents,spouses,children,amount_all_beneficiaries,amount_retired,amount_widowers,old_beneficiaries,state
6,35013,35,15,5,5,5,5,33,20,5,20,Alabama
7,35016,4400,2745,840,325,145,345,5087,3468,370,2945,Alabama
8,35031,2040,1180,425,150,85,200,2273,1473,168,1290,Alabama
9,35049,910,570,165,60,40,75,1089,752,71,610,Alabama
10,35079,2045,1160,455,170,70,190,2557,1614,206,1265,Alabama

In [9]:
all_states['state'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri',
       'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey',
       'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
       'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
       'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah',
       'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin',
       'Wyoming', 'American Samoa', 'Guam', 'Northern Mariana Islands',
       'Puerto Rico', 'U.S. Virgin Islands'], dtype=object)

In [10]:
all_states['amount_per_beneficiary'] = all_states['amount_all_beneficiaries'] / all_states['total']

## Persist data for visualization using Tableau

In [11]:
all_states.to_csv('all_states.csv', index=False)

In [12]:
all_states.sort_values('amount_all_beneficiaries', ascending=False)

,zip_code,total,retired,disabled,widowers_parents,spouses,children,amount_all_beneficiaries,amount_retired,amount_widowers,old_beneficiaries,state,amount_per_beneficiary
601,32162,40345,37055,785,1275,1120,110,60122,55983,1931,37830,Florida,1.4902
610,8759,21775,17910,1600,1460,535,270,30866,25946,2091,19225,New Jersey,1.4175
210,33437,18580,16255,560,925,670,170,28398,25432,1485,17540,Florida,1.52842
414,8831,18155,14985,1030,1060,655,425,28365,24234,1657,16180,New Jersey,1.56238
186,85375,19385,17170,495,990,670,60,27365,24657,1426,18235,Arizona,1.41166
178,85351,19790,16945,960,1305,465,115,26818,23271,1795,18080,Arizona,1.35513
860,10025,17125,13375,1580,820,730,620,25287,21273,1083,14485,New York,1.47661
1679,10314,17825,12030,2400,1240,885,1270,24790,17925,1703,13300,New York,1.39074
609,8757,17370,13720,1590,1225,445,390,24026,19575,1704,14725,New Jersey,1.38319
631,34748,18115,14680,1610,845,500,480,23744,20097,1117,15325,Florida,1.31074
1103,32174,16895,13295,1495,1080,470,555,23184,18977,1508,13910,Florida,1.37224
1358,34293,15765,12870,1145,830,525,395,22047,18570,1200,13350,Florida,1.39848
600,32159,16115,13830,825,785,465,210,21868,19221,1080,14480,Florida,1.357
1096,32137,15660,12310,1400,730,600,620,21739,17892,1011,12725,Florida,1.38819
185,85374,15230,12695,950,685,495,405,21124,18254,955,13285,Arizona,1.387
1505,95648,14895,12080,1010,720,610,475,21006,17838,1004,12860,California,1.41027
281,33908,14425,11895,765,855,645,265,20924,17863,1257,12790,Florida,1.45054
611,15601,15775,11095,1850,1255,665,910,20903,15930,1719,12175,Pennsylvania,1.32507
164,926,20275,13070,2220,1975,1720,1290,20773,14690,1948,15475,Puerto Rico,1.02456
1293,33573,14715,12660,580,890,485,100,20693,18194,1244,13515,Florida,1.40625
266,11234,15440,11100,1855,915,610,960,20571,15681,1216,11915,New York,1.33232
1409,33467,14225,11585,915,765,485,475,20522,17343,1108,12370,Florida,1.44267
299,14221,13530,10500,860,1010,670,490,20373,16684,1540,11640,New York,1.50576
836,10023,11580,9660,520,585,530,285,20001,17491,991,10590,New York,1.7272
213,33446,12745,10905,530,680,530,100,19380,17031,1034,11810,Florida,1.5206
602,32163,11890,10760,385,315,400,30,19200,17628,510,10435,Florida,1.6148
1677,10312,13115,8850,1825,900,645,895,19171,13682,1313,9610,New York,1.46176
622,34711,14130,10770,1435,675,510,740,19080,15383,907,11165,Florida,1.35032
944,44060,13775,10255,1300,1030,535,655,18971,14933,1484,11085,Ohio,1.37721
21,89052,12875,10625,700,565,540,445,18859,16182,831,11140,Nevada,1.46478
...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Montana,NaN
605,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nebraska,NaN
235,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nevada,NaN
290,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New Hampshire,NaN
716,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New Jersey,NaN
406,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New Mexico,NaN
1996,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York,NaN
1040,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,North Carolina,NaN
405,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,North Dakota,NaN
1359,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ohio,NaN
752,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Oklahoma,NaN
483,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Oregon,NaN
2021,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pennsylvania,NaN
101,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rhode Island,NaN
518,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,South Carolina,NaN
396,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,South Dakota,NaN
754,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tennessee,NaN
2392,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Texas,NaN
333,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Utah,NaN
308,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vermont,NaN
1073,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Virginia,NaN
709,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Washington,NaN
808,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,West Virginia,NaN
866,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wisconsin,NaN
188,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wyoming,NaN
11,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,American Samoa,NaN
22,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Guam,NaN
13,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Mariana Islands,NaN
193,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Puerto Rico,NaN
27,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U.S. Virgin Islands,NaN

In [13]:
all_states.sort_values('amount_all_beneficiaries', ascending=True)

,zip_code,total,retired,disabled,widowers_parents,spouses,children,amount_all_beneficiaries,amount_retired,amount_widowers,old_beneficiaries,state,amount_per_beneficiary
1468,54481,15,15,0,0,0,0,5,5,0,15,Illinois,0.333333
16,86044,15,5,0,5,5,0,5,2,1,15,Utah,0.333333
6,80231,20,20,0,0,0,0,6,6,0,20,Missouri,0.3
691,75504,15,5,5,0,0,5,6,2,0,5,Arkansas,0.4
565,19806,25,25,0,0,0,0,6,6,0,25,Maryland,0.24
499,68056,15,15,0,0,0,0,8,8,0,15,Nebraska,0.533333
1379,47876,20,20,0,0,0,0,8,8,0,20,Illinois,0.4
1690,47876,20,20,0,0,0,0,8,8,0,20,Pennsylvania,0.4
2187,47876,15,15,0,0,0,0,8,8,0,15,California,0.533333
390,64147,20,0,10,0,0,10,9,0,0,0,Missouri,0.45
87,25936,15,5,5,0,0,5,9,4,0,5,West Virginia,0.6
122,87420,20,10,0,10,0,0,10,4,4,15,Arizona,0.5
126,86515,20,10,5,0,0,5,10,5,0,10,New Mexico,0.5
71,60539,15,0,0,0,0,15,10,0,0,0,Illinois,0.666667
497,41351,15,5,5,5,0,0,10,3,1,5,Kentucky,0.666667
637,56287,15,10,0,0,0,5,11,9,0,10,Minnesota,0.733333
849,79968,15,10,0,0,0,5,11,9,0,10,Texas,0.733333
270,58311,15,5,0,5,0,5,11,5,2,10,North Dakota,0.733333
546,40574,15,10,5,0,0,0,11,9,0,10,Kentucky,0.733333
131,84057,25,0,10,0,0,15,11,0,0,0,Nevada,0.44
181,58065,15,10,0,0,0,5,11,8,0,5,North Dakota,0.733333
127,99690,15,10,0,0,0,5,12,9,0,10,Alaska,0.8
128,99691,15,10,5,0,0,0,12,8,0,10,Alaska,0.8
293,83343,15,10,0,0,5,0,12,12,0,10,Idaho,0.8
91,99640,15,10,5,0,0,0,12,7,0,10,Alaska,0.8
594,36113,15,5,0,0,0,10,12,6,0,5,Alabama,0.8
1826,76836,15,15,0,0,0,0,12,11,0,10,Texas,0.8
56,59077,15,10,0,0,0,5,12,8,0,10,Montana,0.8
1658,79002,15,10,0,0,5,0,12,9,0,15,Texas,0.8
157,99732,15,15,0,0,0,0,12,12,0,10,Alaska,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Montana,NaN
605,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nebraska,NaN
235,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nevada,NaN
290,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New Hampshire,NaN
716,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New Jersey,NaN
406,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New Mexico,NaN
1996,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York,NaN
1040,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,North Carolina,NaN
405,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,North Dakota,NaN
1359,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ohio,NaN
752,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Oklahoma,NaN
483,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Oregon,NaN
2021,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pennsylvania,NaN
101,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rhode Island,NaN
518,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,South Carolina,NaN
396,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,South Dakota,NaN
754,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tennessee,NaN
2392,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Texas,NaN
333,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Utah,NaN
308,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vermont,NaN
1073,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Virginia,NaN
709,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Washington,NaN
808,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,West Virginia,NaN
866,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wisconsin,NaN
188,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wyoming,NaN
11,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,American Samoa,NaN
22,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Guam,NaN
13,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Mariana Islands,NaN
193,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Puerto Rico,NaN
27,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U.S. Virgin Islands,NaN

In [14]:
all_states['amount_per_beneficiary'] = all_states['amount_all_beneficiaries'] / all_states['total']

In [15]:
all_states.sort_values('amount_per_beneficiary', ascending=False)

,zip_code,total,retired,disabled,widowers_parents,spouses,children,amount_all_beneficiaries,amount_retired,amount_widowers,old_beneficiaries,state,amount_per_beneficiary
833,10020,15,15,0,0,0,0,34,32,0,15,New York,2.26667
1116,77010,45,35,0,5,5,0,97,84,8,45,Texas,2.15556
1410,12604,15,15,0,0,0,0,32,30,0,15,New York,2.13333
1141,94305,560,435,10,30,75,10,1170,1001,58,540,California,2.08929
340,57186,20,20,0,0,0,0,41,39,0,20,South Dakota,2.05
140,55323,20,20,0,0,0,0,40,39,0,20,Minnesota,2
845,10107,15,15,0,0,0,0,30,29,0,15,New York,2
725,37383,35,30,0,5,0,0,69,61,4,30,Tennessee,1.97143
150,7846,20,20,0,0,0,0,39,31,0,20,New Jersey,1.95
519,24595,25,20,0,5,0,0,48,41,4,25,Virginia,1.92
510,70170,20,20,0,0,0,0,38,34,0,20,Louisiana,1.9
625,91210,20,20,0,0,0,0,38,35,0,20,California,1.9
328,60606,250,210,10,10,10,10,471,421,16,225,Illinois,1.884
1903,19480,40,30,0,0,5,5,75,64,0,35,Pennsylvania,1.875
30,89158,40,35,0,0,5,0,75,67,0,40,Nevada,1.875
611,11005,1700,1420,20,210,50,0,3187,2698,400,1675,New York,1.87471
531,7976,330,255,5,25,30,15,618,510,50,295,New Jersey,1.87273
835,10022,7175,5935,180,425,425,210,13411,11682,800,6720,New York,1.86913
299,29603,30,20,0,5,0,5,56,46,5,25,South Carolina,1.86667
847,10111,15,10,5,0,0,0,28,20,0,10,New York,1.86667
204,99791,15,10,0,5,0,0,28,18,6,15,Alaska,1.86667
834,10021,8495,7075,210,555,490,165,15822,13752,1049,7995,New York,1.86251
64,19732,80,65,5,5,5,0,149,131,5,75,Delaware,1.8625
23,2110,455,355,25,20,40,15,847,730,32,420,Massachusetts,1.86154
939,90067,1235,965,15,130,100,25,2285,1897,242,1190,California,1.8502
841,10065,5415,4490,135,380,330,80,10012,8639,717,5130,New York,1.84894
330,60611,5555,4500,200,380,415,60,10241,8749,696,5165,Illinois,1.84356
695,33109,180,155,0,5,15,5,331,298,10,170,Florida,1.83889
843,10075,4780,3940,145,295,285,115,8753,7522,564,4450,New York,1.83117
317,66286,35,25,5,5,0,0,64,48,7,30,Kansas,1.82857
...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Montana,NaN
605,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nebraska,NaN
235,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nevada,NaN
290,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New Hampshire,NaN
716,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New Jersey,NaN
406,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New Mexico,NaN
1996,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York,NaN
1040,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,North Carolina,NaN
405,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,North Dakota,NaN
1359,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ohio,NaN
752,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Oklahoma,NaN
483,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Oregon,NaN
2021,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pennsylvania,NaN
101,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rhode Island,NaN
518,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,South Carolina,NaN
396,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,South Dakota,NaN
754,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tennessee,NaN
2392,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Texas,NaN
333,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Utah,NaN
308,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vermont,NaN
1073,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Virginia,NaN
709,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Washington,NaN
808,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,West Virginia,NaN
866,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wisconsin,NaN
188,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wyoming,NaN
11,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,American Samoa,NaN
22,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Guam,NaN
13,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Mariana Islands,NaN
193,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Puerto Rico,NaN
27,Includes beneficiaries in foreign countries.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U.S. Virgin Islands,NaN

In [16]:
num_features = ['total', 'retired', 'disabled', 'widowers_parents', 'spouses', 
    'children', 'amount_all_beneficiaries', 'amount_retired', 'amount_widowers', 
    'old_beneficiaries', 'amount_per_beneficiary' ]

In [17]:
for feature in num_features:
    all_states[feature] = all_states[feature].astype(float)

In [18]:
all_states = all_states.dropna()

# Q1

In [19]:
per_top = np.percentile(all_states['amount_per_beneficiary'], 95,)
per_bot = np.percentile(all_states['amount_per_beneficiary'], 5)

per_bot, per_top

(0.96842105263157896, 1.4904212040271207)

In [20]:
top_zip_codes = all_states[all_states['amount_per_beneficiary'] > per_top]
bot_zip_codes = all_states[all_states['amount_per_beneficiary'] < per_bot]

In [21]:
top_zip_codes['status'] = 'TOP'
bot_zip_codes['status'] = 'BOT'

extremes = pd.concat([top_zip_codes, bot_zip_codes], axis=0)

In [22]:
extremes.to_csv('extremes_5.csv')

In [26]:
state_details = all_states.groupby('state').agg({'amount_per_beneficiary' : np.mean})